# Настройки данных
data_path: ./           
dataset: clean_movies   
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
load_col:
    inter: [user_id, item_id, rating]

# Гиперпараметры кастомной модели (Адаптивной)
temperature: 0.5
proto_reg_weight: 0.5
centroids_path: 'cluster_centroids.pt'

# Настройки обучения
epochs: 300               
train_batch_size: 2048
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 10

# Настройки оценки
eval_args:
    split: {'RS': [0.8, 0.1, 0.1]}
    group_by: user
    order: RO
    mode: full
metrics: ['Recall', 'NDCG']
topk: [10, 50]
valid_metric: NDCG@10

# System
use_tensorboard: False
gpu_id: 0